### ISSUE TITLE
Invalid link populated in the list of graphs

### ISSUE THREAD

**Issue by ysweid** [GraphLinq/GraphLinq.AppInterface#1]
## What?

As per the screenshot below, the link of the graph is invalid.

<img width="765" alt="Screen Shot 2021-04-15 at 1 53 10 PM" src="https://user-images.githubusercontent.com/7145251/114821921-e33d6f00-9df3-11eb-8086-41cc43fa5168.png">

## How?

Quick check on the source code of the app, I found out that the value of the link is defaulted and never changed.

https://github.com/GraphLinq/GraphLinq.AppInterface/blob/main/src/components/Graphs/GraphCard.tsx#L42

**Comment by jrbgit** [comment]
Thanks - Closing this issue and marking as resolved :)
